version: '3'

volumes:
   db:      { external: { name: "${VOLUME_DB}" }}
   config:  { external: { name: "${VOLUME_CONFIG}" }}
   uploads: { external: { name: "${VOLUME_UPLOADS}" }}
   build:   { external: { name: "${VOLUME_BUILD}" }}

services:
  pleroma:
     build: .
     image: mamemomonga/pleroma:latest
     environment:
       MIX_ENV: prod
     volumes:
       - config:/opt/pleroma/config
       - uploads:/opt/pleroma/uploads
       - build:/opt/pleroma/_build
     depends_on:
       - db
     ports:
       - 4000:4000
     command:
       - server

  db:
     image: postgres:10.7
     volumes:
       - db:/var/lib/postgresql/data
     env_file: .env

